version: '3.3'

services:
  ros:
    build: ./ros
    command: npm --max-old-space-size=4096 start
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - ./ros/keys:/usr/src/app/keys
      - ./ros/src:/usr/src/app/src
      - ./ros/data:/usr/src/app/data
      - ./ros/tsconfig.json:/usr/src/app/tsconfig.json
  node:
    build: ./node
    command: npm start
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - ./node/src:/usr/src/app/src
      - ./node/logs:/root/.npm/_logs/
      - ./node/data:/usr/src/app/data
      - ./node/realm-object-server:/usr/src/app/realm-object-server
      - ./node/realms:/usr/src/app/realms
